/**
 * ARC-Air study data service: the single data-access layer for the frontend.
 *
 * All UI components must load data through these functions, never from
 * hardcoded arrays. Today the functions read the local dataset snapshot
 * (src/app/data/arcair-studies.json, generated by scripts/transform-arcair.mjs
 * from the ARC-Air CSV export).
 *
 * TODO(Django): Replace each function body with a fetch() to the Django REST
 * API once the backend is available. The suggested endpoints are noted on
 * every function. Function signatures and return shapes are designed to stay
 * stable across that swap, so components will not need changes.
 */
import rawDataset from "../data/arcair-studies.json";
import {
  AREA_COORDINATES,
  COUNTRY_CENTROIDS,
  COUNTRY_NAME_ALIASES,
  COUNTRY_TOPO_ID,
} from "../data/geo";
import type {
  ArcAirDataset,
  AreaSummary,
  CountrySummary,
  DatasetStats,
  PagedResult,
  PollutantInfo,
  Study,
  StudyFilters,
  StudyQuery,
} from "../types/arcair";

const dataset = rawDataset as unknown as ArcAirDataset;

// ---------------------------------------------------------------------------
// Normalization helpers
// ---------------------------------------------------------------------------

/** Canonical country display name for a raw dataset country value. */
export function canonicalCountryName(raw: string): string {
  return COUNTRY_NAME_ALIASES[raw] ?? raw;
}

/**
 * Canonical area (city/site) name: strips "City" / "city of" decorations and
 * unifies duplicate spellings so "Tetouan City" and "Tetouan city" merge.
 * Multi-site labels like "Pretoria - Rosslyn" collapse to the parent city.
 */
export function canonicalAreaName(raw: string): string {
  let name = raw.trim().replace(/\.$/, "");
  name = name.replace(/^city of\s+/i, "");
  name = name.replace(/\s+city$/i, "");
  name = name.replace(/^City of\s+/i, "");
  if (/^Pretoria(\s*[-–]| west)/i.test(name) || name === "University of Pretoria") {
    return "Pretoria";
  }
  if (/^Boskrans/.test(name)) return "Boskrans";
  if (/^Khatoum$/i.test(name)) return "Khartoum";
  return name;
}

function areaCoordinates(
  country: string,
  area: string,
): [number, number] | null {
  return (
    AREA_COORDINATES[`${country}|${area}`] ??
    COUNTRY_CENTROIDS[country] ??
    null
  );
}

// ---------------------------------------------------------------------------
// Pre-normalized studies (country names canonicalized once)
// ---------------------------------------------------------------------------

const STUDIES: Study[] = dataset.studies.map((study) => ({
  ...study,
  country: canonicalCountryName(study.country),
}));

const POLLUTANTS: PollutantInfo[] = dataset.pollutants;
const POLLUTANT_BY_KEY = new Map(POLLUTANTS.map((p) => [p.key, p]));

// ---------------------------------------------------------------------------
// Catalog / metadata
// ---------------------------------------------------------------------------

/**
 * Pollutant catalog (keys, names, categories, units).
 * TODO(Django): GET /api/pollutants/
 */
export async function getPollutants(): Promise<PollutantInfo[]> {
  return POLLUTANTS;
}

/** Pollutant catalog grouped by dataset category, in dataset order. */
export async function getPollutantsByCategory(): Promise<
  { category: string; pollutants: PollutantInfo[] }[]
> {
  const groups: { category: string; pollutants: PollutantInfo[] }[] = [];
  const byCategory = new Map<string, PollutantInfo[]>();
  for (const p of POLLUTANTS) {
    let list = byCategory.get(p.category);
    if (!list) {
      list = [];
      byCategory.set(p.category, list);
      groups.push({ category: p.category, pollutants: list });
    }
    list.push(p);
  }
  return groups;
}

/**
 * High-level dataset statistics for headers and analytics.
 * TODO(Django): GET /api/stats/
 */
export async function getDatasetStats(): Promise<DatasetStats> {
  const countries = new Set<string>();
  const areas = new Set<string>();
  let recordCount = 0;
  let yearFrom: number | null = null;
  let yearTo: number | null = null;
  for (const s of STUDIES) {
    countries.add(s.country);
    recordCount += s.records.length;
    for (const r of s.records) {
      if (r.studyArea) areas.add(`${s.country}|${canonicalAreaName(r.studyArea)}`);
    }
    if (s.yearFrom !== null && (yearFrom === null || s.yearFrom < yearFrom))
      yearFrom = s.yearFrom;
    if (s.yearTo !== null && (yearTo === null || s.yearTo > yearTo))
      yearTo = s.yearTo;
  }
  return {
    studyCount: STUDIES.length,
    recordCount,
    countryCount: countries.size,
    areaCount: areas.size,
    yearFrom,
    yearTo,
    pollutantCount: POLLUTANTS.length,
  };
}

/** Distinct dataset regions (e.g. "Northern Africa"), in dataset order. */
export async function getRegions(): Promise<string[]> {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const s of STUDIES) {
    if (s.region && !seen.has(s.region)) {
      seen.add(s.region);
      out.push(s.region);
    }
  }
  return out;
}

/** Distinct site settings from record descriptions (e.g. "Urban- Residential"). */
export async function getSettings(): Promise<string[]> {
  const seen = new Set<string>();
  for (const s of STUDIES)
    for (const r of s.records)
      if (r.description) seen.add(r.description);
  return [...seen].sort();
}

// ---------------------------------------------------------------------------
// Studies: querying, filtering, sorting, pagination
// ---------------------------------------------------------------------------

function studyPollutantKeys(study: Study): Set<string> {
  const keys = new Set<string>();
  for (const r of study.records)
    for (const k of Object.keys(r.measurements)) keys.add(k);
  return keys;
}

function matchesFilters(study: Study, filters: StudyFilters): boolean {
  const query = filters.query?.trim().toLowerCase();
  if (query) {
    const keys = studyPollutantKeys(study);
    const haystack = [
      study.title,
      study.author,
      study.source,
      study.journal,
      study.country,
      study.region,
      ...study.records.map((r) => r.studyArea),
      ...study.records.map((r) => r.description),
      ...study.records.map((r) => r.methodology),
      ...[...keys].map((k) => POLLUTANT_BY_KEY.get(k)?.name ?? k),
    ]
      .join(" \n ")
      .toLowerCase();
    if (!haystack.includes(query)) return false;
  }
  if (filters.countries?.length && !filters.countries.includes(study.country))
    return false;
  if (filters.regions?.length && !filters.regions.includes(study.region))
    return false;
  if (filters.pollutants?.length) {
    const keys = studyPollutantKeys(study);
    if (!filters.pollutants.some((k) => keys.has(k))) return false;
  }
  if (filters.categories?.length) {
    const keys = studyPollutantKeys(study);
    const categories = new Set(
      [...keys].map((k) => POLLUTANT_BY_KEY.get(k)?.category ?? ""),
    );
    if (!filters.categories.some((c) => categories.has(c))) return false;
  }
  if (filters.settings?.length) {
    const ok = filters.settings.some((setting) =>
      study.records.some((r) =>
        r.description.toLowerCase().includes(setting.toLowerCase()),
      ),
    );
    if (!ok) return false;
  }
  if (filters.yearFrom !== undefined && study.yearTo !== null) {
    if (study.yearTo < filters.yearFrom) return false;
  }
  if (filters.yearTo !== undefined && study.yearFrom !== null) {
    if (study.yearFrom > filters.yearTo) return false;
  }
  return true;
}

function sortStudies(items: Study[], sort: StudyQuery["sort"]): Study[] {
  const sorted = [...items];
  switch (sort) {
    case "yearDesc":
      sorted.sort((a, b) => (b.yearTo ?? -1) - (a.yearTo ?? -1));
      break;
    case "yearAsc":
      sorted.sort((a, b) => (a.yearFrom ?? 9999) - (b.yearFrom ?? 9999));
      break;
    case "titleAsc":
      sorted.sort((a, b) => a.title.localeCompare(b.title));
      break;
    case "countryAsc":
      sorted.sort((a, b) => a.country.localeCompare(b.country));
      break;
    default:
      break; // "relevance" keeps dataset order
  }
  return sorted;
}

/**
 * Query studies with filtering, sorting, and pagination.
 * TODO(Django): GET /api/studies/?search=&country=&region=&pollutant=&year_from=&year_to=&ordering=&page=&page_size=
 */
export async function queryStudies(
  query: StudyQuery = {},
): Promise<PagedResult<Study>> {
  const filters = query.filters ?? {};
  const filtered = sortStudies(
    STUDIES.filter((s) => matchesFilters(s, filters)),
    query.sort ?? "relevance",
  );
  const pageSize = query.pageSize ?? 20;
  const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize));
  const page = Math.min(Math.max(1, query.page ?? 1), pageCount);
  return {
    items: filtered.slice((page - 1) * pageSize, page * pageSize),
    total: filtered.length,
    page,
    pageSize,
    pageCount,
  };
}

/**
 * Fetch one study by id.
 * TODO(Django): GET /api/studies/{id}/
 */
export async function getStudyById(id: number): Promise<Study | undefined> {
  return STUDIES.find((s) => s.id === id);
}

// ---------------------------------------------------------------------------
// Map aggregates
// ---------------------------------------------------------------------------

let countrySummariesCache: CountrySummary[] | null = null;

/**
 * Country summaries with per-area aggregates for the map view.
 * Optionally filtered (same filters as queryStudies) so the map can react
 * to pollutant category filters.
 * TODO(Django): GET /api/map/countries/ (optionally with the same filter params)
 */
export async function getCountrySummaries(
  filters?: StudyFilters,
): Promise<CountrySummary[]> {
  if (!filters && countrySummariesCache) return countrySummariesCache;

  const relevant = filters
    ? STUDIES.filter((s) => matchesFilters(s, filters))
    : STUDIES;

  const byCountry = new Map<string, CountrySummary>();
  for (const study of relevant) {
    if (!byCountry.has(study.country)) {
      byCountry.set(study.country, {
        topoId: COUNTRY_TOPO_ID[study.country] ?? null,
        name: study.country,
        region: study.region,
        studyCount: 0,
        recordCount: 0,
        yearFrom: null,
        yearTo: null,
        areas: [],
        studies: [],
      });
    }
    const summary = byCountry.get(study.country)!;
    summary.studyCount++;
    summary.recordCount += study.records.length;
    summary.studies.push(study);
    if (
      study.yearFrom !== null &&
      (summary.yearFrom === null || study.yearFrom < summary.yearFrom)
    )
      summary.yearFrom = study.yearFrom;
    if (
      study.yearTo !== null &&
      (summary.yearTo === null || study.yearTo > summary.yearTo)
    )
      summary.yearTo = study.yearTo;

    const areasByName = new Map(summary.areas.map((a) => [a.name, a]));
    const seenAreasForStudy = new Set<string>();
    for (const record of study.records) {
      const rawArea = record.studyArea || study.country;
      const name = canonicalAreaName(rawArea);
      const coordinates = areaCoordinates(study.country, name) ??
        areaCoordinates(study.country, rawArea);
      if (!coordinates) continue;
      let area = areasByName.get(name);
      if (!area) {
        area = {
          name,
          country: study.country,
          coordinates,
          studyCount: 0,
          settings: [],
          studies: [],
        };
        areasByName.set(name, area);
        summary.areas.push(area);
      }
      if (!seenAreasForStudy.has(name)) {
        seenAreasForStudy.add(name);
        area.studyCount++;
        area.studies.push({
          id: study.id,
          source: study.source,
          title: study.title,
        });
      }
      if (record.description && !area.settings.includes(record.description))
        area.settings.push(record.description);
    }
  }

  const result = [...byCountry.values()];
  for (const summary of result)
    summary.areas.sort((a, b) => b.studyCount - a.studyCount);
  result.sort((a, b) => b.studyCount - a.studyCount);

  if (!filters) countrySummariesCache = result;
  return result;
}

/** All mapped study areas across countries (for the "Cities" map mode). */
export async function getAllAreas(
  filters?: StudyFilters,
): Promise<AreaSummary[]> {
  const summaries = await getCountrySummaries(filters);
  return summaries.flatMap((c) => c.areas);
}
